name: Melon Ticket Checker

on:
  workflow_dispatch: # 手动触发，方便测试
  schedule:
    - cron: "0 * * * *" # 每小时执行一次，可以调整

jobs:
  check-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install axios @slack/webhook

      - name: Run ticket checker
        env:
          PRODUCT_ID: 211358        # 你的 productId
          SCHEDULE_ID: 100001       # 你的 scheduleId
          SEAT_ID: 1_0              # 你的 seatId
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # 推荐用 secrets 管理
          MESSAGE: "有票了~"
        run: node your-script.js
