name: mes
on:
  workflow_dispatch: {}
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 211309
          schedule-id: 100002
          seat-id: 1_0
          slack-incoming-webhook-url: ${{ secrets.TEST }}
          message: '有票了!!'

